apiVersion: v1
kind: Pod
metadata:
  namespace: wp
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-cntr
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_DATABASE
      value: exampledb
    - name: MYSQL_USER
      value: exampleuser
    - name: MYSQL_PASSWORD
      value: examplepass
    - name: MYSQL_RANDOM_ROOT_PASSWORD
      value: '1'
---
kind: Service
apiVersion: v1
metadata:
  namespace: wp
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
