apiVersion: v1
kind: Pod
metadata:
  name: odoo-pod
  labels:
    app: odoo
  namespace: odoo  
spec:
  containers:
  - name: odoo-container
    image: odoo
    ports:
    - containerPort: 8069
    env:
    - name: HOST
      value: pgsql-service
    - name: USER
      value: odoo
    - name: PASSWORD
      value: kanzalpass

---
apiVersion: v1
kind: Service
metadata:
  name: odoo-svc
  namespace: odoo
spec:
  type: NodePort
  selector:
    app: odoo
  ports:
  - protocol: TCP
    port: 8069
    targetPort: 8069
    nodePort: 30090
